### ISSUE TITLE
Return error types instead of `log.Fatal`

### ISSUE THREAD

**Issue by spenserblack** [irevenko/octostats#1]
I discovered this when looking into irevenko/octotui#2. When the error mentioned in that issue occurs, a `log.Fatal` call in `AllContributions` causes `octotui` to exit with stats code 1. However, because the failure is occurring here, the error can't be handled in octotui. This can be an issue because, if octotui fails when calling `AllContributions`, the terminal's state isn't reset, which can result in issues like the cursor remaining hidden.

In general, I think that code that forces a program to quit should be kept out of a library as much as possible, and should instead be handled by error types. Panics/fatal errors should instead be in code for a binary unless *absolutely necessary* in the library code.

If it's alright with you, I'll make a PR to replace `log.Fatal` calls with error returns. :slightly_smiling_face:
This will likely be a breaking change by changing return types, though, and may require a `v2` release.

**Comment by irevenko** [comment]
Yeees, please create such PR 🙏.
I'll rewrite octotui myself

**Comment by irevenko** [comment]
Gonna do this now, was bussy with this project - [https://github.com/irevenko/koneko](url)
